baseURL = 'https://kakudokentaro.com/'
languageCode = 'ja'
title = 'Kakudo Kentaro'

[permalinks]
  blog = '/:sections/:year/:month/:day/:filename/'

[taxonomies]
  tag = '/blog/tags/'

[markup]
  [markup.highlight]
    style = 'github'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # For raw HTML
