baseURL = 'https://kakudokentaro.com/'
languageCode = 'ja-jp'
title = 'Kakudo Kentaro'
disableKinds = ["RSS", "sitemap"]

[permalinks]
  'blog' = '/:sections/:year/:month/:day/:filename/'

[markup]
  [markup.highlight]
    style = 'github'
    tabWidth = 2
