baseURL = 'https://kakudokentaro.com/'
languageCode = 'ja-jp'
title = 'Kakudo Kentaro'
theme = "soboku"
disableKinds = ["RSS", "sitemap"]

[permalinks]
  'blog' = '/:sections/:year/:month/:day/:filename/'
