baseURL = 'https://kakudokentaro.com/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'Kakudo Kentaro'
disableKinds = ['taxonomyTerm'] # Unknown why this works.
hasCJKLanguage = true

[taxonomies]
  tag = 'tags'

[permalinks]
  '/blog' = '/:sections/:year/:month/:day/:filename/'
  '/tags' = '/blog/tags/:slug'

[markup]
  [markup.highlight]
    style = 'github'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # For raw HTML
